---
- name: Install MySQL Server
  apt:
    name: mysql-server
    state: present
  become: yes

- name: Start MySQL service
  service:
    name: mysql
    state: started
    enabled: yes
  become: yes

- name: Ensure MySQL is running
  service:
    name: mysql
    state: started
    enabled: yes
  become: yes

