---
- name: Deploy and configure MySQL database server
  hosts: database_servers
  become: yes
  vars:
    mysql_db_name: "mydatabase"
    mysql_db_user: "myuser"
    mysql_db_password: "mypassword"
    backup_dir: "/var/backups/mysql"
    backup_script_path: "/usr/local/bin/backup.sh"

  tasks:
    - name: Install MySQL
      apt:
        update_cache: yes
        name: "{{ item }}"
        state: present
      with_items:
      - mysql-server
      - mysql-client
      - python3-mysqldb
      - libmysqlclient-dev

    - name: Copy MySQL configuration file
      template:
        src: /home/einfochips/Day17_1/Ansible-Day17/templates/mysql.cnf.j2
        dest: /etc/mysql/mysql.conf.d/mysqld.cnf
      notify: Restart MySQL

    - name: Ensure MySQL service is running
      service:
        name: mysql
        state: started
        enabled: yes

    - name: Create MySQL database
      mysql_db:
        name: "{{ mysql_db_name }}"
        state: present

    - name: Create MySQL user and grant privileges
      mysql_user:
        name: "{{ mysql_db_user }}"
        password: "{{ mysql_db_password }}"
        priv: '*.*:ALL'
        host: '%'
        state: present

    - name: Create backup directory
      file:
        path: "{{ backup_dir }}"
        state: directory
        mode: '0755'

    - name: Copy MySQL backup script
      copy:
        src: /home/einfochips/Day17_1/Ansible-Day17/scripts/backup.sh
        dest: /usr/local/bin/mysql_backup.sh
        mode: '0755'

    - name: Set up cron job for daily backups
      cron:
        name: "Daily MySQL backup"
        minute: "0"
        hour: "2"
        job: "{{ backup_script_path }} {{ mysql_db_name }} {{ mysql_db_user }} {{ mysql_db_password }} {{ backup_dir }}"
    
  handlers:
    - name: Restart MySQL
      service:
        name: mysql
        state: restarted
